messages:
  no_permissions: 'У вас недостаточно прав'
  usage:
    create: '&#FF5555▶ &7Использование: &f/loot create <название>'
    edit: '&#FF5555▶ &7Использование: &f/loot edit <название>'
    give: '&#FF5555▶ &7Использование: &f/loot give <игрок> <название_лута> <кол-во>'
    info: '&#FF5555▶ &7Использование: &f/loot info <название>'
    remove: '&#FF5555▶ &7Использование: &f/loot remove <название>'
    swap: '&#FF5555▶ &fИспользование: &7/loot swap <название_лута|all>'
  loot_already_exists: '&#FF5555▶ &fЛут с таким названием &7уже существует&f!'
  loot_not_found: '&#FF5555▶ &fЛут с таким названием &7отсутствует&f!'
  loot_not_found_give: '&#FF5555▶ &fЛут с таким названием &7отсутствует&f!'
  loot_created: '&#55FF55▶ &fЛут &#55FF55{name} &fуспешно создан!'
  loot_deleted: '&#55FF55▶ &fЛут &#55FF55{name} &fуспешно удален!'
  player_only: '&#FF5555▶ &fДанная команда доступна только &7игрокам&f!'
  player_not_found: '&#FF5555▶ &fИгрок &7{player} &fне найден или offline!'
  editing_loot: '&#55FF55▶ &fОткрытие редактора лута &#55FF55{name}'
  invalid_number_format: "&#FF5555▶ &fНеверный формат числа '{number}'"
  give_success: '&#55FF55▶ &fЛут &#55FF55{loot} &fвыдан игроку &7{player}'
  give_received: '&#55FF55▶ &fВы получили лут &#55FF55{loot}'
  loot_info_header: '&#FFAA00▶ &6Информация о луте:'
  loot_info_name: '&#55FFFF▪ &fНазвание: &7{name}'
  loot_info_items: '&#55FFFF▪ &fПредметов: &7{count}'
  loot_list_empty: '&#FFAA00▶ &fСозданные луты &7отсутствуют&f!'
  loot_list_header: '&#55FF55▶ &aСписок лутов &7({count}):'
  loot_list_entry: '&#55FFFF{number}. &7{name}'
  config_reloaded: '&#55FF55▶ &fКонфигурация плагина успешно &7перезагружена&f!'
  opening_loots_menu: '&#55FF55▶ &fОткрытие меню лутов...'
  swap_invalid_offhand: '&#FF5555▶ &fДля замены предмета возьмите его во вторую руку!'
  swap_invalid_mainhand: '&#FF5555▶ &fВы не можете заменить предмет на воздух!'
  swap_same_item: '&#FF5555▶ &fПредметы для замены не должны быть одинаковыми!'
  swap_item_not_found: '&#FFAA00▶ &fПредмет &7{item} &fне был найден в указанном луте.'
  swap_success_all: '&#55FF55▶ &fУспешно заменено &a{amount} &fпредметов во &aвсех &fлутах'
  swap_success_single: '&#55FF55▶ &fУспешно заменено &a{amount} &fпредметов в луте &a{loot}'